ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/lpm/inc/

obj-y += mtk_lpm_module.o
obj-y += mtk_lpm_call.o
obj-y += mtk_lpm_registry.o
obj-y += mtk_lpm_fs/
#obj-y += mtk_lpm_trace_event/
obj-y += platform/
obj-y += modules/
obj-$(CONFIG_MTK_LPM_DBG_COMMON) += power_gs_v1/
