# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the phy drivers.
#

ccflags-y	+= -I$(srctree)/drivers/usb/mtu3/

obj-$(CONFIG_PHY_MTK_TPHY)		+= phy-mtk-tphy.o
obj-$(CONFIG_PHY_MTK_UFS)		+= phy-mtk-ufs.o
obj-$(CONFIG_PHY_MTK_XSPHY)		+= phy-mtk-xsphy.o
obj-$(CONFIG_PHY_MTK_FPGAPHY)		+= phy-mtk-fpga.o
obj-$(CONFIG_PHY_MTK_PCIE)		+= phy-mtk-pcie.o
