#
# Makefile for the Mediatek SoCs built-in ethernet macs
#

obj-$(CONFIG_NET_MEDIATEK_SOC)			+= mtk_sgmii_pwr.o \
						   mtk_eth_soc.o mtk_sgmii.o \
						   mtk_eth_path.o \
						   mtk_edma.o
obj-$(CONFIG_NET_MEDIATEK_DBG)			+= mtk_eth_dbg.o
