/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (c) 2019 MediaTek Inc.
 */

#ifndef __pcm_def_h__
#define __pcm_def_h__

/*
 * Auto generated by DE, please DO NOT modify this file directly.
 */

/* --- R0 Define --- */
#define R0_SC_26M_CK_OFF              (0x1U << 0)
#define R0_SC_TX_TRACK_RETRY_EN       (0x1U << 1)
#define R0_SC_MEM_CK_OFF              (0x1U << 2)
#define R0_SC_AXI_CK_OFF              (0x1U << 3)
#define R0_SC_DR_SRAM_LOAD            (0x1U << 4)
#define R0_SC_MD26M_CK_OFF            (0x1U << 5)
#define R0_SC_DPY_MODE_SW             (0x1U << 6)
#define R0_SC_DMSUS_OFF               (0x1U << 7)
#define R0_SC_DPY_2ND_DLL_EN          (0x1U << 8)
#define R0_SC_DR_SRAM_RESTORE         (0x1U << 9)
#define R0_SC_MPLLOUT_OFF             (0x1U << 10)
#define R0_SC_TX_TRACKING_DIS         (0x1U << 11)
#define R0_SC_DPY_DLL_EN              (0x1U << 12)
#define R0_SC_DPY_DLL_CK_EN           (0x1U << 13)
#define R0_SC_DPY_VREF_EN             (0x1U << 14)
#define R0_SC_PHYPLL_EN               (0x1U << 15)
#define R0_SC_DDRPHY_FB_CK_EN         (0x1U << 16)
#define R0_SC_DPY_BCLK_ENABLE         (0x1U << 17)
#define R0_SC_MPLL_OFF                (0x1U << 18)
#define R0_SC_SHU_RESTORE             (0x1U << 19)
#define R0_SC_CKSQ0_OFF               (0x1U << 20)
#define R0_SC_DR_SHU_LEVEL_SRAM_LATCH (0x1U << 21)
#define R0_SC_DR_SHU_EN               (0x1U << 22)
#define R0_SC_DPHY_PRECAL_UP          (0x1U << 23)
#define R0_SC_MPLL_S_OFF              (0x1U << 24)
#define R0_SC_DPHY_RXDLY_TRACK_EN     (0x1U << 25)
#define R0_SC_PHYPLL_SHU_EN           (0x1U << 26)
#define R0_SC_PHYPLL2_SHU_EN          (0x1U << 27)
#define R0_SC_PHYPLL_MODE_SW          (0x1U << 28)
#define R0_SC_PHYPLL2_MODE_SW         (0x1U << 29)
#define R0_SC_DR_SHU_LEVEL0           (0x1U << 30)
#define R0_SC_DR_SHU_LEVEL1           (0x1U << 31)
/* --- R7 Define --- */
#define R7_PWRAP_SLEEP_REQ             (0x1U << 0)
#define R7_EMI_CLK_OFF_REQ             (0x1U << 1)
#define R7_PCM_BUS_PROTECT_REQ         (0x1U << 2)
#define R7_SPM_CK_UPDATE               (0x1U << 3)
#define R7_SPM_CK_SEL0                 (0x1U << 4)
#define R7_SPM_CK_SEL1                 (0x1U << 5)
#define R7_SPM_LEAVE_DEEPIDLE_REQ      (0x1U << 6)
#define R7_FREQH_PAUSE_MPLL            (0x1U << 7)
#define R7_SC_26M_CK_SEL               (0x1U << 8)
#define R7_PCM_TIMER_SET               (0x1U << 9)
#define R7_PCM_TIMER_CLR               (0x1U << 10)
#define R7_SPM_LEAVE_SUSPEND_REQ       (0x1U << 11)
#define R7_CSYSPWRUPACK                (0x1U << 12)
#define R7_IM_SLEEP_ENABLE             (0x1U << 13)
#define R7_SRCCLKENO                   (0x1U << 14)
#define R7_FORCE_DDREN_ON              (0x1U << 15)
#define R7_SPM_APSRC_INTERNAL_ACK      (0x1U << 16)
#define R7_CPU_SYS_TIMER_CLK_SEL       (0x1U << 17)
#define R7_SC_AXI_DCM_DIS              (0x1U << 18)
#define R7_FREQH_PAUSE_MEM             (0x1U << 19)
#define R7_FREQH_PAUSE_MAIN            (0x1U << 20)
#define R7_SRCCLKENO1                  (0x1U << 21)
#define R7_WDT_KICK_P                  (0x1U << 22)
#define R7_SPM2EMI_S1_MODE_ASYNC       (0x1U << 23)
#define R7_SC_DDR_PST_REQ              (0x1U << 24)
#define R7_SC_DDR_PST_ABORT_REQ        (0x1U << 25)
#define R7_PMIC_IRQ_REQ_EN             (0x1U << 26)
#define R7_FORCE_VTCXO_ON              (0x1U << 27)
#define R7_FORCE_APSRC_ON              (0x1U << 28)
#define R7_FORCE_INFRA_ON              (0x1U << 29)
#define R7_FORCE_VRF18_ON              (0x1U << 30)
#define R7_SPM_DDR_EN_INTERNAL_ACK     (0x1U << 31)
/* --- R2 Define --- */
#define R2_MD32PCM_IRQ_TRIG_BIT        (0x1U << 31)
/* --- R12 Define --- */
#define R12_PCM_TIMER         (0x1U << 0)
#define R12_SPM_DEBUG         (0x1U << 1)
#define R12_KP_IRQ            (0x1U << 2)
#define R12_APWDT_EVENT       (0x1U << 3)
#define R12_APXGPT_EVENT      (0x1U << 4)
#define R12_CONN2AP_WAKEUP    (0x1U << 5)
#define R12_EINT_EVENT        (0x1U << 6)
#define R12_CONN_WDT_IRQ      (0x1U << 7)
#define R12_CCIF0_EVENT       (0x1U << 8)
#define R12_LOWBATTERY_IRQ    (0x1U << 9)
#define R12_SSPM2SPM_WAKEUP   (0x1U << 10)
#define R12_NETSYS_WAKEUP     (0x1U << 11)
#define R12_MHCCIF_WAKEUP     (0x1U << 12)
#define R12_PCM_WDT_WAKE      (0x1U << 13)
#define R12_USB0_CDSC         (0x1U << 14)
#define R12_USB0_POWERDWN     (0x1U << 15)
#define R12_SYS_TIMER         (0x1U << 16)
#define R12_EINT_EVENT_SECURE (0x1U << 17)
#define R12_CCIF1_EVENT       (0x1U << 18)
#define R12_UART0_IRQ         (0x1U << 19)
#define R12_AFE_IRQ_MCU       (0x1U << 20)
#define R12_THERM_CTRL_EVENT  (0x1U << 21)
#define R12_SYS_CIRQ_IRQ      (0x1U << 22)
#define R12_MD2AP_PEER_WAKEUP (0x1U << 23)
#define R12_CSYSPWREQ         (0x1U << 24)
#define R12_MD_WDT            (0x1U << 25)
#define R12_AP2AP_PEER_WAKEUP (0x1U << 26)
#define R12_SEJ               (0x1U << 27)
#define R12_CPU_WAKEUP        (0x1U << 28)
#define R12_SSUSB             (0x1U << 29)
#define R12_PCIE_BRIDGE_IRQ   (0x1U << 30)
#define R12_PCIE_WAKEUP       (0x1U << 31)
/* --- R12ext Define --- */
#define R12EXT_26M_WAKE               (0x1U << 0)
#define R12EXT_26M_SLEEP              (0x1U << 1)
#define R12EXT_INFRA_WAKE             (0x1U << 2)
#define R12EXT_INFRA_SLEEP            (0x1U << 3)
#define R12EXT_APSRC_WAKE             (0x1U << 4)
#define R12EXT_APSRC_SLEEP            (0x1U << 5)
#define R12EXT_VRF18_WAKE             (0x1U << 6)
#define R12EXT_VRF18_SLEEP            (0x1U << 7)
#define R12EXT_DVFS_WAKE              (0x1U << 8)
#define R12EXT_DDREN_WAKE             (0x1U << 9)
#define R12EXT_DDREN_SLEEP            (0x1U << 10)
#define R12EXT_MCU_PM_WFI             (0x1U << 11)
#define R12EXT_SSPM_IDLE              (0x1U << 12)
#define R12EXT_CONN_SRCCLKENB         (0x1U << 13)
#define R12EXT_DRAMC_MD32_WFI         (0x1U << 14)
#define R12EXT_SW_MAILBOX_WAKE        (0x1U << 15)
#define R12EXT_SSPM_MAILBOX_WAKE      (0x1U << 16)
#define R12EXT_ADSP_MAILBOX_WAKE      (0x1U << 17)
#define R12EXT_SCP_MAILBOX_WAKE       (0x1U << 18)
#define R12EXT_SPM_LEAVE_SUSPEND_ACK  (0x1U << 19)
#define R12EXT_SPM_LEAVE_DEEPIDLE_ACK (0x1U << 20)
#define R12EXT_VS1_TRIGGER            (0x1U << 21)
#define R12EXT_VS2_TRIGGER            (0x1U << 22)
#define R12EXT_CROSS_REQ_APU          (0x1U << 23)
#define R12EXT_CROSS_REQ_L3           (0x1U << 24)
#define R12EXT_DDR_PST_ACK            (0x1U << 25)
/* --- R13 Define --- */
#define R13_SRCCLKENI0              (0x1U << 0)
#define R13_SRCCLKENI1              (0x1U << 1)
#define R13_MD_SRCCLKENA_0          (0x1U << 2)
#define R13_MD_APSRC_REQ_0          (0x1U << 3)
#define R13_CONN_DDR_EN             (0x1U << 4)
#define R13_MD_SRCCLKENA_1          (0x1U << 5)
#define R13_MD32_SRCCLKENA          (0x1U << 6)
#define R13_MD32_APSRC_REQ          (0x1U << 7)
#define R13_MD1_STATE               (0x1U << 8)
#define R13_MM_STATE                (0x1U << 10)
#define R13_MD32_STATE              (0x1U << 11)
#define R13_MD_DDR_EN_0             (0x1U << 12)
#define R13_CONN_STATE              (0x1U << 13)
#define R13_CONN_SRCCKENA           (0x1U << 14)
#define R13_CONN_APSRC_REQ          (0x1U << 15)
#define R13_SC_DDR_PST_ACK          (0x1U << 16)
#define R13_SC_DDR_PST_ABORT_ACK    (0x1U << 17)
#define R13_CPUEB_WFI               (0x1U << 18)
#define R13_CSYSPWRUPREQ            (0x1U << 19)
#define R13_PWRAP_SLEEP_ACK         (0x1U << 20)
#define R13_EMI_CLK_OFF_ACK         (0x1U << 21)
#define R13_AUDIO_DSP_STATE         (0x1U << 22)
#define R13_SW_DMDRAMCSHU_ACK       (0x1U << 23)
#define R13_CONN_SRCCLKENB          (0x1U << 24)
#define R13_SC_DR_SRAM_LOAD_ACK     (0x1U << 25)
#define R13_INFRA_AUX_IDLE          (0x1U << 26)
#define R13_DVFS_STATE              (0x1U << 27)
#define R13_SC_DR_SRAM_PLL_LOAD_ACK (0x1U << 28)
#define R13_SC_DR_SRAM_RESTORE_ACK  (0x1U << 29)
#define R13_MD_VRF18_REQ_0          (0x1U << 30)
#define R13_DDR_EN_STATE            (0x1U << 31)


enum SPM_WAKE_SRC_LIST {
	WAKEUP_BY_PCM_TIMER = (1U << 0),
	WAKEUP_BY_SPM_DEBUG = (1U << 1),
	WAKEUP_BY_KP_IRQ = (1U << 2),
	WAKEUP_BY_APWDT_EVENT = (1U << 3),
	WAKEUP_BY_APXGPT_EVENT = (1U << 4),
	WAKEUP_BY_CONN2AP_WAKEUP = (1U << 5),
	WAKEUP_BY_EINT_EVENT = (1U << 6),
	WAKEUP_BY_CONN_WDT_IRQ = (1U << 7),
	WAKEUP_BY_CCIF0_EVENT = (1U << 8),
	WAKEUP_BY_LOWBATTERY_IRQ = (1U << 9),
	WAKEUP_BY_SSPM2SPM_WAKEUP = (1U << 10),
	WAKEUP_BY_NETSYS_WAKEUP = (1U << 11),
	WAKEUP_BY_MHCCIF_WAKEUP = (1U << 12),
	WAKEUP_BY_PCM_WDT_WAKE = (1U << 13),
	WAKEUP_BY_USB0_CDSC = (1U << 14),
	WAKEUP_BY_USB0_POWERDWN = (1U << 15),
	WAKEUP_BY_SYS_TIMER = (1U << 16),
	WAKEUP_BY_EINT_EVENT_SECURE = (1U << 17),
	WAKEUP_BY_CCIF1_EVENT = (1U << 18),
	WAKEUP_BY_UART0_IRQ = (1U << 19),
	WAKEUP_BY_AFE_IRQ_MCU = (1U << 20),
	WAKEUP_BY_THERM_CTRL_EVENT = (1U << 21),
	WAKEUP_BY_SYS_CIRQ_IRQ = (1U << 22),
	WAKEUP_BY_MD2AP_PEER_WAKEUP = (1U << 23),
	WAKEUP_BY_CSYSPWREQ = (1U << 24),
	WAKEUP_BY_MD_WDT = (1U << 25),
	WAKEUP_BY_AP2AP_PEER_WAKEUP= (1U << 26),
	WAKEUP_BY_SEJ = (1U << 27),
	WAKEUP_BY_CPU_WAKEUP = (1U << 28),
	WAKEUP_BY_SSUSB = (1U << 29),
	WAKEUP_BY_PCIE_BRIDGE_IRQ = (1U << 30),
	WAKEUP_BY_PCIE_WAKEUP = (1U << 31)
};

extern const char *wakesrc_str[32];

/* define WAKE_SRC_CONN2AP for conn use */
#define WAKE_SRC_CONN2AP WAKE_SRC_STA1_CONN2AP_SPM_WAKEUP_B

#endif /* __pcm_def_h__ */
